// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://idwdwbfuqqbthvvdiakg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlkd2R3YmZ1cXFidGh2dmRpYWtnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE1MzgyNzEsImV4cCI6MjA1NzExNDI3MX0.H32g6NQS1cKurb3LqNBz0Myhg1lz-Hco0CBKADNNb7s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);